### ISSUE TITLE
gorm v1 compatibilty for qor integration

### ISSUE THREAD

**Issue by ghost** [longbridgeapp/nested-set#15]
Hi guys,

Hope you are all well !

I wanted to try your awesome script with QOR framework and their [admin](https://github.com/qor/admin) package.

But unfortunately they have not migrated yet to the latest version of gorm.

How complicated it would be to make it compatible so I can integrate it in their admin panel ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by griffinqiu** [comment]
I am sorry. We are not support the old version gorm.

However, In the first edition go-nested-set have been implemented by sql. I believe it work as well in old version gorm. 

Please check at:

https://github.com/griffinqiu/go-nested-set/tree/v1.0.0

I hope this helps you.
